(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[387,393,82,160],[302,0,210,253],[302,255,193,136],[0,0,300,600],[302,393,83,160]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.fourteenbottomleft = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.fourteenbottomright = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.fourteenpietopleft = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.fourteentable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.fourteentopright = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.sweetinspiration = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AhtBvQgLgDAAgKQAAgIALgEIAFgDQAGgDADgHQACgIAAgRIAAgPIgBgSIAAgWQAAgkgBgKQgCgLgEgCIgLgEQgOgFAAgHQAAgFAFgDQAEgEAKgEIAggLIAXgEQAGABADADQADADAAAIIAAAPIAAACIABAAIACAAIABgBIAFgFIAFgEQAYgWAbgBQAQABAPAGQAPAIAKALQALAMAEARQAEASAAAjIAAAeIAAAOIAAAOQAAAPACAHQACAGAGADIAGADQALAEAAAIQAAAJgLAEQgKADgiAAQggAAgKgDQgLgEAAgIQAAgJALgDIAJgFQAFgCACgKQACgKAAgYQAAhHgJgSQgJgRgYgBQgLABgLAHQgKAHgGAMQgFAJgCASQgCARAAAsQAAAVACAIQACAHAEACIAJAFQALADAAAJQAAAIgLAEQgLADgdABQgigBgLgDg");
	this.shape.setTransform(97,31.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AhRBUQggghAAgyQAAgyAighQAhgiAyAAQAwAAAfAgQAfAfAAAxQAAAzghAjQgiAigwAAQgwABggghgAgqhCQgOASAAAeQAAArATAeQATAfAaAAQAWAAAOgTQANgSAAgfQAAgqgTgfQgTgdgZAAQgWAAgOASg");
	this.shape_1.setTransform(71.2,31.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgnCgQgLgEAAgKQAAgHALgEIAFgDQAGgDADgHQACgIAAgRIAAgPIgBgSIAAgXQABgkgCgJQgCgLgEgCIgLgEQgNgFAAgHQgBgFAFgEQAEgEAKgEIAhgLIAXgEQAGAAADAEQACAFAAAKIAAANIAAAKIgCA5IAAABIgBA3QAAAVACAJQADAJAEACIAJAEQALAEAAAJQABAIgLAEQgMADgdAAQghAAgLgDgAgbhwQgJgIAAgMQAAgMAKgJQALgJAPAAQANAAAKAIQAKAIAAAMQAAAMgLAJQgLAJgOAAQgOAAgKgIg");
	this.shape_2.setTransform(52.2,26.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgLCGQgMgDgIgIQgHgGgEgNQgDgMAAgiIAAh3IgVAAIgGgCIgCgFIAAgGQAAgHAXgUIAKgIIAIgIQAYgUAIAAIAGACQADACAAADIAAAqIAyAAQAFAAADADQABABAAAHIAAAFQAAAGgCACQgCADgFAAIguAAIgEACIgBAFIAABvQAAAcAFAIQAFAHANAAQAHAAALgEIAPgDQAFAAADACQAEADAAAFQAAAMgTAMQgTALgZAAQgMAAgLgEg");
	this.shape_3.setTransform(38.1,29.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AAnBpIgLgMIgKAFQgbATgbAAQgiAAgTgTQgVgTABgfQAAgkAagTQAZgUAvAAQALAAAGAEQAFADAAAIQAAANgPAAQgWAAgOAKQgNALAAATQAAASAMALQAMAKATAAQAVAAAJgJQAKgKAAgXIAAhVQAAgTgJgLQgJgLgOAAQgLAAgKAFQgJAFgJAKIgEAGQgOARgPAAQgKAAgFgGQgFgFAAgKQAAgVAagOQAagPApAAQAYAAASAHQARAGALANQAGAIADAOQACAOABAgIAABHQgBANADAGQACAGAFABIAHACQAOAEgBAIQABALgPAIQgQAJgTAAQgLAAgLgMg");
	this.shape_4.setTransform(18.4,31.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AhDBvQgLgDAAgKQAAgIALgEIAGgDQAGgDACgHQACgIAAgRIAAgPIAAgSIAAgNQAAgogCgNQgCgNgEgCIgLgEQgNgFAAgHQAAgFAEgEQAEgEAKgDIAegKIAUgFQALAAADAfIABAEIABABQAMgRAMgKQANgKAMAAQAQAAAJAKQAJAJAAAQQAAAPgHAKQgHAJgNAAIgLgDIgJgGIgFgJQgDgGgCAAQgQAAgGAWQgFAVAABDQAAAUACAJQACAKAGACIAJAEQAOAEAAAJQAAAIgNAEQgMADgeABQgigBgLgDg");
	this.shape_5.setTransform(-1.9,31.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgnCgQgLgEAAgKQAAgHALgEIAFgDQAHgDACgHQACgIAAgRIAAgPIgBgSIAAgXQAAgkgBgJQgCgLgEgCIgLgEQgOgFABgHQAAgFAEgEQAEgEAKgEIAigLIAWgEQAHAAACAEQADAFAAAKIAAANIAAAKIgDA5IAAABIgBA3QAAAVACAJQADAJAEACIAJAEQAMAEgBAJQAAAIgLAEQgLADgdAAQghAAgLgDgAgbhwQgKgIAAgMQAAgMALgJQAKgJAPAAQAPAAAJAIQAKAIAAAMQAAAMgLAJQgLAJgOAAQgPAAgJgIg");
	this.shape_6.setTransform(-17.4,26.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AhsCYQgMgDAAgKQAAgHAKgEIAMgGQAEgEABgSQADgRAAg4IAAgkQAAg9gDgRQgBgSgGgDIgKgEQgOgEAAgIQAAgFAEgEQAFgEAJgDIAfgKQAOgEAJAAQAGAAADADQACAEAAAIIAAALIABAEIAAABIAJgGIAJgGQAOgKAMgFQANgFANAAQApAAAbAeQAbAfAAAwQAAA1gfAjQgdAiguAAQgTAAgHgFQgIgGAAgJQAAgFAFgDQACgEAIAAIAFABIAHABQAaAAAPgVQAOgUAAgiQAAgmgQgYQgQgXgZAAQgXAAgNANQgOANAAAhIAACOIABAWQACAJACADQADADAKADIAIADIAGAEIABAHQABAIgNAEQgOADgfAAQghAAgLgEg");
	this.shape_7.setTransform(-37.5,35.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgRB0IgXgDIgHADIgGABIgFgBIgFgCQgHgHgHgSQgGgRAAgRQAAgHAEgFQADgFAGAAQAKAAALASIAIAOQAIAJALAEQAMAGAMAAQAPAAAIgIQAJgHAAgNQAAgSglgSIgNgHQgigRgNgOQgMgPAAgUQAAgeAUgSQAUgSAhgBIAPABIAPADIALgEIAHgCQALABAKARQALASAAATQAAAIgEAFQgDAEgHAAQgFAAgFgEQgEgEgHgLQgJgOgIgFQgKgGgMAAQgMAAgIAHQgIAIAAALQAAALAIAHQAIAJAbAOIADABQA+AdAAAkQAAAggXAVQgZAVgkgBg");
	this.shape_8.setTransform(-59.9,31.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AhtBvQgLgDAAgKQAAgIALgEIAFgDQAGgDADgHQACgIAAgRIAAgPIgBgSIAAgWQAAgkgBgKQgCgLgEgCIgLgEQgOgFAAgHQAAgFAFgDQAEgEAKgEIAggLIAXgEQAGABADADQADADAAAIIAAAPIAAACIABAAIACAAIABgBIAFgFIAFgEQAYgWAbgBQAQABAPAGQAPAIAKALQALAMAEARQAEASAAAjIAAAeIAAAOIAAAOQAAAPACAHQACAGAGADIAGADQALAEAAAIQAAAJgLAEQgKADgiAAQggAAgKgDQgLgEAAgIQAAgJALgDIAJgFQAFgCACgKQACgKAAgYQAAhHgJgSQgJgRgYgBQgLABgLAHQgKAHgGAMQgFAJgCASQgCARAAAsQAAAVACAIQACAHAEACIAJAFQALADAAAJQAAAIgLAEQgLADgdABQgigBgLgDg");
	this.shape_9.setTransform(-82.8,31.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AgvCeQgMgEAAgKQAAgJAOgGIAJgEQAGgEABgbQACgaAAhGIgBhUQgCghgDgEQgCgDgMgFQgMgFAAgJQAAgJAKgDQAKgDAnAAQAoAAAKADQAKADAAAJQAAAKgOAEIgKAGQgEADgBAXIgDBJIACBqQABAnADADQACAEAMAEQAMAFAAAJQAAAKgMAEQgNADgjABQgigBgNgDg");
	this.shape_10.setTransform(-103.2,26.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AgLCGQgMgDgIgIQgHgHgEgMQgDgMAAgiIAAh3IgVAAIgGgCIgCgFIAAgGQAAgHAXgUIAKgIIAIgIQAYgUAIAAIAGACQADACAAADIAAAqIAyAAQAFAAADADQABABAAAHIAAAFQAAAGgCACQgCADgFAAIguAAIgEACIgBAFIAABvQAAAcAFAIQAFAHANAAQAHAAALgEIAPgDQAFAAADADQAEADAAAEQAAAMgTAMQgTALgZAAQgMAAgLgEg");
	this.shape_11.setTransform(55.1,-23.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AhIBVQgggiAAgvQAAg0AhgiQAggiAzAAQArABAZAYQAZAYAAAqQAAAPgEAEQgEAEgRAAIhVAAQgHAAgEgEQgEgDAAgHQAAgFAEgEQAEgDAHAAIAuAAIALgBQADgCAAgFQAAgVgOgPQgPgPgUAAQgbAAgMAXQgNAYAAAgQAAAjARAZQASAZAcABQAQgBAMgDQALgEALgIIAIgGQALgJAHAAQAEAAAEAEQADADAAAEQAAAGgGAHQgFAIgKAIQgTAQgSAHQgSAGgWAAQguAAgggfg");
	this.shape_12.setTransform(35.2,-21.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AhIBVQgggiAAgvQAAg0AhgiQAggiAzAAQArABAZAYQAZAYAAAqQAAAPgEAEQgEAEgRAAIhVAAQgHAAgEgEQgEgDAAgHQAAgFAEgEQAEgDAHAAIAuAAIALgBQADgCAAgFQAAgVgOgPQgPgPgUAAQgbAAgMAXQgNAYAAAgQAAAjARAZQASAZAcABQAQgBAMgDQALgEALgIIAIgGQALgJAHAAQAEAAAEAEQADADAAAEQAAAGgGAHQgFAIgKAIQgTAQgSAHQgSAGgWAAQguAAgggfg");
	this.shape_13.setTransform(11.6,-21.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AANAYIgbhFQgMgggLgFIgGgDQgNgFAAgJQAAgJALgDQALgDAkgBQAeABALADQALADAAAJIgCAIIgEADIgIAEQgIAEgBAFIAFAOIASAvIATArQAFAJADAAQADAAAEgFIAKgUIAYg4QAIgWAAgHIgCgIIgFgFIgGgDQgKgDAAgIQAAgJAKgDQAKgDAcgBQAXABAKADQAJADAAAJQAAAJgMAEIgHADQgLAFgUAuIgFAMIgJAUQgzB0gPAAQgOAAgohcgAiDAMIgGgNIgPgmQgOgmgLgFIgGgDQgNgFAAgJQAAgJALgDQALgDAlgBQAfABAKADQALADAAAJIgCAIIgDADIgIAEQgJAEAAAFIAFASIARArIASApQAGALADAAQAHAAAGgNIAHgQIAFgHQADgCAGAAQAEAAAEADQADADAAAGQAAAFgGANQgYA0gKAQQgKARgIABQgQAAgshog");
	this.shape_14.setTransform(-18.2,-21.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("Ag2ChQgagFgQgJQgIgGgGgTQgGgTAAgZQAAgKAEgGQAEgFAIAAQAKAAALAUIAFAJQAPAZAQAMQARALAXAAQAYAAARgPQARgOAAgVQAAgghCgdIgHgDQg2gXgSgUQgSgUAAgfQAAgoAegaQAegaAvAAIAaACIAeAHIAJgFIAIgCQAFAAAFADQAEADAFAJQAIAOAEAOQAEAPABALQgBAIgDAEQgEAEgGAAQgMAAgLgQIgEgEQgMgRgPgIQgPgIgSAAQgZAAgOAMQgOALAAAVQAAASALAMQAMAMAwAVIAJAEQAoAQASAQQAMALAGAPQAHAPAAASQAAAuggAZQggAag4AAQgbAAgYgGg");
	this.shape_15.setTransform(-50,-26.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.sweetinspiration, new cjs.Rectangle(-112.5,-55.2,225,110.4), null);


(lib.seventeenwhatsinourfest = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgRB1IgXgFIgHAFIgHABIgEgBIgFgEQgHgFgGgSQgHgTAAgQQAAgHAEgFQAEgFAFAAQALAAAKASIAJANQAGAKAMAFQALAEANAAQAOAAAJgGQAJgIAAgNQAAgSglgTIgMgFQgjgSgNgOQgMgPAAgVQAAgdAUgSQAUgSAhAAIAPABIAQACIAKgEIAHgBQALgBALATQAKARAAAUQAAAHgDAEQgEAFgGAAQgGAAgFgEQgEgFgIgLQgHgNgKgGQgIgFgNAAQgMAAgIAHQgIAIAAAMQAAAJAIAJQAIAHAbAOIADABQA+AeAAAlQAAAfgYAVQgYAUgkABg");
	this.shape.setTransform(70.6,6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AhIBUQggggAAgxQAAgzAhghQAggjAzABQArgBAZAZQAZAZAAAqQAAAOgEAEQgEAEgRAAIhVAAQgHAAgEgDQgEgEAAgGQAAgHAEgCQAEgDAHAAIAuAAIALgCQADgCAAgFQAAgVgOgPQgPgPgUAAQgbAAgMAYQgNAWAAAiQAAAhARAaQASAZAcAAQAQABAMgEQALgEALgHIAIgHQALgJAHAAQAEAAAEADQADAEAAAEQAAAFgGAJQgFAHgKAHQgTARgSAHQgSAHgWAAQgugBggggg");
	this.shape_1.setTransform(49.2,6.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AhsCYQgLgDAAgKQAAgHAJgEIALgGQAFgEACgSQABgRAAg4IAAgkQAAg9gBgRQgCgSgGgDIgKgEQgOgEAAgIQAAgFAFgEQAEgEAIgDIAggKQAPgEAHAAQAHAAACADQADAEABAIIAAALIAAAEIABABIAJgGIAIgGQAOgKAMgFQANgFANAAQAqAAAaAeQAbAfAAAwQAAA1geAjQgeAiguAAQgTAAgHgFQgHgGgBgJQABgFAEgDQACgEAHAAIAGABIAIABQAYAAAPgVQAPgUAAgiQAAgmgQgYQgRgXgZAAQgXAAgNANQgNANAAAhIAACOIACAWQAAAJADADQADADAKADIAJADIAEAEIACAHQAAAIgMAEQgOADgfAAQghAAgLgEg");
	this.shape_2.setTransform(23.6,10);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgnCgQgLgEAAgKQAAgHALgEIAGgDQAFgDADgHQACgIAAgRIAAgPIAAgSIAAgXQgBgkgBgJQgBgLgFgCIgKgEQgOgFgBgHQABgFAEgEQAEgEAKgEIAhgLIAYgEQAFAAADAEQACAFABAKIAAANIAAAKIgCA5IAAABIgBA3QAAAVACAJQABAJAGACIAIAEQAMAEAAAJQgBAIgKAEQgLADgeAAQghAAgLgDgAgbhwQgKgIAAgMQAAgMALgJQALgJAOAAQAOAAAKAIQAJAIAAAMQAAAMgKAJQgKAJgPAAQgPAAgJgIg");
	this.shape_3.setTransform(4.5,1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AhGBUQggggAAgxQAAgzAighQAigjAwABQAmgBAZAUQAaATAAAaQAAAKgHAHQgHAGgMAAQgLAAgHgFQgHgFgIgTQgGgQgJgGQgJgHgOAAQgYABgOASQgPAUgBAiQABAoAUAYQAVAZAfAAQAMAAAKgCQAJgEAJgFIAJgHQALgJAHAAQAFAAACACQAEADAAAFQAAAFgGAJQgEAHgHAGQgSAQgTAIQgTAGgXABQgugBgfggg");
	this.shape_4.setTransform(-13.1,6.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AhIBUQggggAAgxQAAgzAhghQAggjAzABQArgBAZAZQAZAZAAAqQAAAOgEAEQgEAEgRAAIhVAAQgHAAgEgDQgEgEAAgGQAAgHAEgCQAEgDAHAAIAuAAIALgCQADgCAAgFQAAgVgOgPQgPgPgUAAQgbAAgMAYQgNAWAAAiQAAAhARAaQASAZAcAAQAQABAMgEQALgEALgHIAIgHQALgJAHAAQAEAAAEADQADAEAAAEQAAAFgGAJQgFAHgKAHQgTARgSAHQgSAHgWAAQgugBggggg");
	this.shape_5.setTransform(-36.5,6.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AAwBvQgVhHgQgOQgPgPgXAAQgRABAAgPQAAgOAOABQAlAAASgPQARgOAAgfQAAgdgSgPQgSgPgiAAQgRAAgHACQgGADgDAGIgCATIgBAtIAABjIACBDQABAPAEAEIAKAEQAOAGAAAJQAAAKgNADQgMAEgjAAQgjAAgNgEQgMgDAAgKQAAgKAOgFIAJgFQAFgDACgbQACgaAAhHIgBhUQgCgggDgFQgDgDgMgFQgLgEAAgJQAAgIAHgEQAGgEAOAAIAxAAIAtgBIAkgBQAwAAAaAVQAaAVAAAoQAAAdgRAVQgRAWgfAJIAAACQAYAEAOAPQANAPALAlIAGAWQAIAiAOAAIAGAAIAIgBQAEABAEADQADAEAAAEQAAALgNAGQgMAHgVAAQgtAAgPg1g");
	this.shape_6.setTransform(-63.8,1.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AhmCUQgMgKABgOQgBgLAJgIQAHgIAMAAIAKACIAHAEIAFAJQAGAJAEAAQAMAAALgRQAMgQAAgSQAAgSgPgkIgDgFIgkhOIgUgsQgEgHgNgGIgBAAQgHgEgDgDQgCgDAAgFQAAgKALgDQAMgEAhAAQAhAAALAEQALADAAAJIgCAHIgEAEIgIAEQgJADABAEIAEARIASAtIARAqQAHALACgBQACAAAGgKIAPgkIAQgsQAFgQAAgFQAAgHgMgHQgNgHAAgFQAAgJAKgCQALgEAZAAQAbAAAJAEQAJADAAAJQAAAIgMADIgJAEQgNAGgOAnIgHAQIgcBIQglBdgXAcQgYAcghAAQgQAAgKgJg");
	this.shape_7.setTransform(113.9,-42.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AhhCHQgbgeAAgxQAAg2AeghQAfgjAvABIAQACQAHACAEAEQADAFAAAGQAAAMgOAAIgGgBIgGAAQgZAAgPAUQgPATAAAkQAAAmARAXQAQAYAZAAQAXAAANgNQANgNAAgZIAAg+IAAhmQAAgPgDgGQgDgHgJgCIgGgDQgNgDAAgIQAAgGAFgEQAFgEARgHIAZgHIAVgCQAIAAADADQADAFAAAKIAAALIgCCJIABBfQACAUADADIAQAFQAMADAAAIQAAAKghALIgWAGIgRACQgGAAgDgEQgDgDAAgHIAAgLIAAgFIgCgBIgHAEIgJAIQgOAKgMAFQgNAEgNAAQgqAAgageg");
	this.shape_8.setTransform(90,-52.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AAnBpIgLgMIgKAFQgbATgbAAQgiAAgTgTQgVgTABgfQAAgkAagTQAZgUAvAAQALAAAGAEQAFADAAAIQAAANgPAAQgWAAgOAKQgNALAAATQAAASAMALQAMAKATAAQAVAAAJgJQAKgKAAgXIAAhVQAAgTgJgLQgJgLgOAAQgLAAgKAFQgJAFgJAKIgEAGQgOARgPAAQgKAAgFgGQgFgFAAgKQAAgVAagOQAagPApAAQAYAAASAHQARAGALANQAGAIADAOQACAOABAgIAABHQgBANADAGQACAGAFABIAHACQAOAEgBAIQABALgPAIQgQAJgTAAQgLAAgLgMg");
	this.shape_9.setTransform(64.3,-47.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AhIBUQggggAAgxQAAgzAhgiQAgghAzAAQArAAAZAYQAZAZAAAqQAAAOgEAEQgEAEgRAAIhVAAQgHAAgEgDQgEgEAAgGQAAgHAEgCQAEgDAHgBIAuAAIALgBQADgCAAgFQAAgWgOgOQgPgPgUAAQgbAAgMAXQgNAXAAAiQAAAhARAaQASAaAcgBQAQABAMgEQALgEALgHIAIgGQALgKAHAAQAEAAAEADQADADAAAFQAAAFgGAJQgFAHgKAHQgTARgSAHQgSAHgWAAQgugBggggg");
	this.shape_10.setTransform(40.3,-47.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AAwBvQgVhGgQgPQgPgPgXAAQgRAAAAgOQAAgOAOABQAlAAASgPQARgOAAgfQAAgdgSgPQgSgPgiAAQgRAAgHACQgGADgDAGIgCATIgBAtIAABjIACBDQABAPAEAEIAKAEQAOAFAAAKQAAAJgNAEQgMAEgjAAQgjAAgNgEQgMgEAAgJQAAgKAOgFIAJgFQAFgDACgbQACgaAAhHIgBhUQgCgggDgEQgDgEgMgFQgLgEAAgJQAAgIAHgEQAGgEAOAAIAxAAIAtgBIAkgBQAwAAAaAVQAaAVAAAoQAAAdgRAVQgRAWgfAJIAAACQAYAEAOAPQANAPALAlIAGAWQAIAiAOAAIAGAAIAIgBQAEABAEADQADADAAAFQAAALgNAGQgMAHgVAAQgtAAgPg1g");
	this.shape_11.setTransform(13,-52);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgsAXQgHAAgCgCQgDgDAAgGIACgKIAFgMQADgHADgCQADgCAKAAIAKAAIAUABIAmgCIAGAAQAHAAADACQADADAAAGQAAAMgHALQgHAKgKAAIgLAAIgMgBIgxACIgFAAg");
	this.shape_12.setTransform(-11.2,-47.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AhnCUQgKgKgBgOQAAgLAIgIQAJgIAKAAIAKACIAHAEIAHAJQAFAJAFAAQALAAALgRQAMgQAAgSQAAgSgPgkIgDgFIgjhOIgVgsQgEgHgNgGIgBAAQgHgEgDgDQgDgDAAgFQAAgKAMgDQAMgEAhAAQAgAAALAEQALADAAAJIgBAHIgEAEIgIAEQgIADAAAEIAEARIASAtIARAqQAHALACgBQADAAAFgKIAPgkIAQgsQAFgQAAgFQAAgHgMgHQgNgHAAgFQAAgJALgCQAJgEAaAAQAaAAAKAEQAKADAAAJQAAAIgNADIgKAEQgMAGgPAnIgGAQIgdBIQgkBdgXAcQgYAcghAAQgQAAgLgJg");
	this.shape_13.setTransform(-29.8,-42.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgLCHQgMgEgIgIQgHgGgEgNQgDgNAAghIAAh3IgVAAIgGgBIgCgHIAAgFQAAgHAXgUIAKgIIAIgHQAYgVAIAAIAGACQADACAAADIAAAqIAyAAQAFAAADACQABADAAAFIAAAGQAAAGgCADQgCACgFAAIguAAIgEACIgBAFIAABuQAAAdAFAHQAFAIANAAQAHAAALgEIAPgEQAFAAADADQAEAEAAAEQAAAMgTAMQgTALgZAAQgMAAgLgDg");
	this.shape_14.setTransform(-49,-49.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AhDBvQgLgDAAgLQAAgHALgEIAGgCQAGgEACgHQACgIAAgQIAAgQIAAgSIAAgNQAAgpgCgMQgCgMgEgDIgLgEQgNgFAAgHQAAgFAEgEQAEgEAKgEIAegKIAUgDQALgBADAfIABAFIABABQAMgTAMgJQANgJAMAAQAQAAAJAJQAJAJAAAQQAAAQgHAIQgHAKgNgBIgLgCIgJgHIgFgJQgDgFgCAAQgQAAgGAVQgFAWAABDQAAATACAKQACAKAGADIAJADQAOAEAAAJQAAAJgNADQgMADgeAAQgiAAgLgDg");
	this.shape_15.setTransform(-65.1,-47.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AAoBpIgMgMIgKAFQgbATgcAAQggAAgVgTQgTgTAAgfQAAgkAagTQAagUAuAAQALAAAGAEQAFADAAAIQAAANgPAAQgWAAgNAKQgOALAAATQAAASAMALQAMAKATAAQAVAAAJgJQAKgKAAgXIAAhVQAAgTgJgLQgJgLgOAAQgLAAgJAFQgKAFgJAKIgFAGQgNARgPAAQgJAAgGgGQgFgFAAgKQAAgVAagOQAagPApAAQAYAAASAHQASAGAKANQAGAIADAOQADAOgBAgIAABHQABANACAGQACAGAEABIAIACQANAEAAAIQAAALgOAIQgQAJgTAAQgLAAgKgMg");
	this.shape_16.setTransform(-85.8,-47.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AhzCfQgNgEAAgKQAAgJAOgFIAJgGQAFgDADgaQABgbAAhGIgBhUQgCghgDgEQgCgDgMgFQgMgFAAgJQAAgIAHgDQAGgFAPAAIAXAAIAZAAIAtgBIAkgBQAyAAAZAWQAZAVAAArQAAAvgfAYQgfAYg7AAQgWABAAgPQAAgQATAAQAcAAARgPQASgPgBggQAAgggRgOQgSgPgkAAQgQABgGACQgHACgCAGIgCAVIgCAvIAABiIACA/QABARAEADIAKAFQAOAFAAAJQAAAKgNAEQgLADgkAAQgjAAgMgDg");
	this.shape_17.setTransform(-110.8,-52.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenwhatsinourfest, new cjs.Rectangle(-126.9,-80.9,253.9,110.4), null);


(lib.seventeenrollovervideo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("AnuCsQhHABgzgzQgzgyABhIQgBhGAzgzQAzgyBHAAIPdAAQBIAAAyAyQAzAzgBBGQABBIgzAyQgyAzhIgBg");
	this.shape.setTransform(0,5,1.067,1.029);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenrollovervideo, new cjs.Rectangle(-71.2,-12.7,142.5,35.5), null);


(lib.seventeenrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AnuCsQhHABgzgzQgzgyABhIQgBhGAzgzQAzgyBHAAIPdAAQBIAAAyAyQAzAzgBBGQABBIgzAyQgyAzhIgBg");
	this.shape.setTransform(0,5,1.067,1.029);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenrectangle, new cjs.Rectangle(-71.2,-12.7,142.5,35.5), null);


(lib.ordernow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AguA1IAAhpIAlAAQAJAAAKADQAKADAIAGQAJAHAFAKIAEALIABAMIgBAMIgEALIgGAJIgIAIQgIAHgKADQgNADgGAAgAgfAoIATAAQAJAAAHgCQAJgEAFgFQAGgEAEgIIACgIIABgJIgBgIIgCgIQgEgIgGgFQgFgFgJgCQgHgEgJAAIgTAAg");
	this.shape.setTransform(44.3,5.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgiA1IAAhpIBDAAIAAANIg0AAIAAAgIAxAAIAAALIgxAAIAAAkIA2AAIAAANg");
	this.shape_1.setTransform(34.2,5.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAUA1IgagvIgQAAIAAAvIgPAAIAAhpIAiAAQAHAAAHACQAHABAFAEQAFADADAGQADAFAAAIQAAAMgHAHIgIAFQgFADgGAAIAeAxgAgWgFIARAAIAJgBIAIgDQADgDACgDQACgDAAgFQAAgFgCgDQgCgDgDgCIgIgDIgIgBIgSAAg");
	this.shape_2.setTransform(25.2,5.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgHA1IAAhpIAOAAIAABpg");
	this.shape_3.setTransform(18.2,5.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgiA1IAAhpIAgAAQAIAAAHACQAHABAFAEQAFADACAGQADAGAAAHQAAAJgDAFQgDAGgFADQgFADgHABQgHACgIAAIgQAAIAAAvgAgTgFIAPAAIAJgBIAIgDIAFgGQACgDAAgFQAAgFgCgDQgCgDgDgCIgIgDIgIgBIgQAAg");
	this.shape_4.setTransform(12,5.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgTA0QgKgEgGgHIALgKQAFAFAGAEQAGADAHAAIAHgBQADgBAEgCQACgCACgEQACgDAAgFQAAgFgCgDQgCgDgDgCIgIgEIgIgEIgKgDQgGgBgDgEQgEgDgDgFQgCgFAAgHQAAgIADgGQADgGAGgDQAEgEAHgCQAGgCAHAAIAJABIAIADQAIADAEAFIgKALQgDgFgFgCQgFgDgHAAIgHABIgHADIgFAFQgBAEAAAEQAAAEABADIAFAFIAHAEIAIADIALADIAKAFQAEADADAGQADAFAAAIQAAAIgDAGQgDAGgFAEQgFAEgHACQgHACgGAAQgKAAgJgEg");
	this.shape_5.setTransform(2.9,5.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAaA1Ig3hWIAABWIgPAAIAAhpIATAAIA2BTIABAAIAAhTIAPAAIAABpg");
	this.shape_6.setTransform(-7,5.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgGA1IAAhpIANAAIAABpg");
	this.shape_7.setTransform(-14.8,5.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgHA1IAAhcIgiAAIAAgNIBSAAIAAANIghAAIAABcg");
	this.shape_8.setTransform(-24.9,5.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgiA1IAAhpIBDAAIAAANIg0AAIAAAgIAxAAIAAALIgxAAIAAAkIA2AAIAAANg");
	this.shape_9.setTransform(-33.3,5.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgNA0QgLgEgHgIQgIgHgEgKQgEgLAAgMQAAgLAEgLQAEgKAIgHIAIgHIAKgFQAKgEALAAIAMABIALADQAKAEAHAGIgLALQgFgFgHgDIgIgDIgJgBQgIAAgHAEQgIADgFAGQgFAGgDAIQgDAHAAAIQAAAJADAIQADAHAFAGQAFAGAIADQAHAEAJAAQAHAAAHgCIALgEIAAgdIgYAAIAAgMIAmAAIAAAzQgIAEgKADIgWACQgLAAgKgEg");
	this.shape_10.setTransform(-44.2,5.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ordernow, new cjs.Rectangle(-51.8,-6.2,103.7,22.4), null);


(lib.mainsides = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("Ag2BAIgEgBQgCgCgBgDIAAhzQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAQABAAAAgBQABAAABAAQAAAAABAAIAvAAIAOABIAMADQANAFAJAJQAJAIAGAMIAEAMIACANQgBAOgFANIgGALIgJAJIgKAHIgMAFQgNAFgNAAgAgjgnQgCACAAAEIAABFQAAABAAAAQAAABABAAQAAABAAAAQABABAAAAIAGACIAWAAQAJAAAIgDQAIgDAHgGQAFgFAEgHQAEgJgBgJQABgIgEgIQgEgIgFgFQgHgGgIgDQgIgDgJAAIgWAAQgEAAgCACg");
	this.shape.setTransform(112.6,-79.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgrBAIgEgBQgBgBAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAAh2QAAAAAAAAQAAgBAAAAQAAgBABAAQAAAAABAAIAEgCIBZAAQAAAAABAAQAAABABAAQAAAAAAABQABAAAAABIABADIAAAFIAAADIgBAFIgDADIhCAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAgBAAQAAABgBAAQAAABAAAAQgBABAAABQAAAAAAABIAAARQAAAAAAABQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAQABAAAAAAIArAAQAAAAABABQAAAAAAAAQABAAAAAAQAAABABAAIABAEIAAAGIAAACQAAAGgFACIgpAAQgCgBgDADQAAABgBAAQAAABAAAAQgBABAAAAQAAABAAABIAAATQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAABABAAQAAAAABABQAAAAABAAQABAAAAAAIBCAAQAEACAAAFIAAAEIgBAFIgBAFQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAg");
	this.shape_1.setTransform(99.1,-79.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AACBAIgEAAIgGAAQgDgCAAgEIAAheQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBgBQgBgBgFAAIgKAAIgKAAIgEAAQgEAAgCgCIgBgHIAAgDIABgFIACgDIADgBIBYAAQAEAAABACQACADAAADIgBADIAAAFIgCAEQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIgZAAQgEABgCABQgCABAAAEIABBdQAAABAAAAQAAABgBABQAAAAAAABQAAAAgBABIgEABg");
	this.shape_2.setTransform(86.9,-79.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AAgBBIgDgBIgCgBIgCgBIgWgjIgDgEQgDgBgDAAIgQAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAABQgBAAAAABQgBAAAAABQAAAAAAABQAAABAAAAIAAAgQAAAAgBABQAAAAAAABQAAAAgBAAQAAABgBAAIgEACIgFAAIgEAAQgEAAgCgCQgCgBAAgEIAAh1QAAgBAAAAQAAgBAAgBQABAAAAAAQAAgBAAAAIAFgBIA2AAQAKAAAIADQAIADAGAFQAGAGADAIQAEAIAAAKQAAALgEAHQgEAGgFAEIgJAHQgEACAAADIAAADIAFAHIAHAKIAHALIADAGIgCAEIgDADIgFACIgEAAgAgagpQgCACAAAEIAAAcQAAAEACACQADABADAAIAaAAIAJgBIAHgEQAEgCACgEQACgEgBgGQABgKgIgGIgHgEIgJgBIgaAAIgGABg");
	this.shape_3.setTransform(75.6,-79.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AAvBAIgHAAQgEgBgBgDIgHgSIgDgCQAAAAAAgBQgBAAAAAAQgBAAAAAAQAAAAgBAAIgrAAIgBAAIgCACIgCABIgBAAIgHASIgDACIgDABIgEABIgEAAIgCAAIgFAAIgDgCQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIA0h5QAAAAABAAQAAgBAAAAQABAAAAgBQABAAAAAAIAEgBIAFAAQAEABABACIAyB5IAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAAAIgEABIgFABgAgBgUIgBACIgCAEIgCAFIgEAIIgDAGIgBAGIgBADIABACQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAZAAIACgCIABgCIgCgGIgDgJIgFgLIgDgHQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAAAAAg");
	this.shape_4.setTransform(62.2,-79.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AACBAIgEAAIgGAAQgDgCAAgEIAAheQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBgBQgBgBgFAAIgKAAIgKAAIgEAAQgEAAgCgCIgBgHIAAgDIABgFIACgDIADgBIBYAAQAEAAABACQACADAAADIgBADIAAAFIgCAEQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIgZAAQgEABgCABQgCABAAAEIABBdQAAABAAAAQAAABgBABQAAAAAAABQAAAAgBABIgEABg");
	this.shape_5.setTransform(50.7,-79.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgcA+QgOgGgKgJIgBgDIgBgCIABgEIAEgFIAFgDIAEgBQADAAADACIAJAGIAKAFQAHACAIAAIAJAAIAKgDQAFgDADgDQADgEAAgGQAAgFgDgDQgEgDgGgCIgOgCIgNgDIgPgDQgIgCgFgDQgHgEgDgGQgDgGgBgKQAAgKAGgIQAFgHAHgFQAIgEAJgDQAKgCAHAAIANABIANADIAMAFIAKAHIABACIAAADQAAAAAAABQAAABAAAAQAAABAAAAQgBABAAAAIgEAEIgFADIgFABIgEAAQgGgGgIgDQgHgEgJAAIgIABIgJADQgEACgDADQgDAEABAFQgBAHAHADQAGADAIABIATADQALABAKAEQAIADAHAHQAGAHAAANQAAALgGAIQgEAIgJAFQgIAGgKACQgKADgIAAQgOAAgOgFg");
	this.shape_6.setTransform(39.1,-79.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgFBDIgDgBIgCgCIgBgCIAAguIgCgHIgDgGIgkg5IAAgBIABgEIAEgDIAFgDIAEAAIAEAAIADADIAaAqIACACIADABIACgBIADgCIAagqIADgDIAEgBIAEABIAFACIAEADQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAAACIgBABIglA5IgDAIIgBACIAAADIAAAuQgCAEgEABIgHAAg");
	this.shape_7.setTransform(21.6,-79.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AACBAIgEAAIgGAAQgDgCAAgEIAAheQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBgBQgBgBgFAAIgKAAIgKAAIgEAAQgEAAgCgCIgBgHIAAgDIABgFIACgDIADgBIBYAAQAEAAABACQACADAAADIgBADIAAAFIgCAEQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIgZAAQgEABgCABQgCABAAAEIABBdQAAABAAAAQAAABgBABQAAAAAAABQAAAAgBABIgEABg");
	this.shape_8.setTransform(10.5,-79.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AAgBBIgCgBIgEgBIgBgBIgWgjIgDgEQgDgBgDAAIgQAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAgBABQAAAAAAABQgBAAAAABQAAAAAAABQgBABAAAAIAAAgQAAAAAAABQAAAAAAABQAAAAgBAAQAAABgBAAIgEACIgFAAIgEAAQgEAAgCgCQgCgBAAgEIAAh1QAAgBAAAAQAAgBAAgBQABAAAAAAQAAgBABAAIADgBIA2AAQALAAAHADQAJADAGAFQAGAGADAIQAEAIAAAKQAAALgEAHQgEAGgFAEIgJAHQgEACAAADIAAADIAFAHIAIAKIAHALIACAGIgBAEIgFADIgEACIgFAAgAgagpQgCACgBAEIAAAcQABAEACACQACABADAAIAaAAIAKgBIAIgEQADgCACgEQABgEABgGQAAgKgHgGIgIgEIgKgBIgaAAIgFABg");
	this.shape_9.setTransform(-0.9,-79.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AAuBAIgGAAQgDgBgCgDIgHgSIgDgCQAAAAAAgBQgBAAAAAAQgBAAAAAAQgBAAAAAAIgqAAIgCAAIgCACIgCABIgBAAIgHASIgDACIgDABIgEABIgDAAIgEAAIgEAAIgDgCQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBgBAAAAIA1h5QAAAAABAAQAAgBAAAAQABAAAAgBQAAAAABAAIAEgBIAFAAQADABABACIA0B5IAAAAQAAABgBAAQAAABAAAAQAAABAAAAQgBAAAAAAIgEABIgEABgAgBgUIgBACIgBAEIgDAFIgEAIIgCAGIgDAGIgBADIABACQABABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIAZAAIADgCIAAgCIgBgGIgFgJIgEgLIgDgHQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAgBAAg");
	this.shape_10.setTransform(-14.2,-79.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AgtBBQgFAAgCgEIAAh5QAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIADgBIA3AAQAJAAAIADQAIACAHAGQAGAFAEAHQADAIAAAJIgBAGIgBAGQgFAMgIAFQgJAGgKACQgLACgKAAIgWgBIgCABIgBACQgBAAAAABQAAAAAAABQgBAAAAABQAAABAAAAIAAAoIgDADIgEABIgEAAgAgbgnQgCACAAADIAAAVIACAEQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIAfAAIAIgBQAEgBADgDQADgCABgDQACgEAAgEQAAgEgCgDQgBgDgDgCIgGgDIgHgCIggAAQgDAAgCADg");
	this.shape_11.setTransform(-26.2,-79.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgrBAIgEgBQgBgBAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAAh2QAAAAAAAAQAAgBAAAAQAAgBABAAQAAAAABAAIAEgCIBZAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAABABIABADIAAAFIAAADIgBAFIgDADIhCAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAgBAAQAAABgBAAQAAABAAAAQgBABAAABQAAAAAAABIAAARQAAAAAAABQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAQABAAAAAAIArAAQAAAAABABQAAAAAAAAQABAAAAAAQABABAAAAIABAEIAAAGIAAACQAAAGgFACIgpAAQgCgBgDADQAAABgBAAQAAABAAAAQgBABAAAAQAAABAAABIAAATQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAABABAAQAAAAABABQAAAAABAAQABAAAAAAIBCAAQAEACAAAFIAAAEIgBAFIgBAFQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAg");
	this.shape_12.setTransform(-44.4,-79.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AAiBBIgFgDIAAguQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBgBAAQgBgDgEAAIgqAAQgDAAgDADQgCADAAACIAAAsQAAABAAAAQAAABgBAAQAAABAAAAQgBAAgBABIgEABIgEAAIgFAAIgFgBQAAgBgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIAAh5IADgDIAFgCIAEAAIAFAAQAEAAADAFIAAApQAAABAAAAQAAABAAABQABAAAAABQAAAAABABQAAAAABABQAAAAABAAQAAABABAAQAAAAABAAIAsAAQADAAACgCQADgCgBgDIAAgpQADgEAEAAIAIgBIAFABQACABACADIAAB5QgCAEgEABIgIAAg");
	this.shape_13.setTransform(-58.1,-79.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AACBAIgEAAIgGAAQgDgCAAgEIAAheQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBgBQgBgBgFAAIgKAAIgKAAIgEAAQgEAAgCgCIgBgHIAAgDIABgFIACgDIADgBIBYAAQAEAAABACQACADAAADIgBADIAAAFIgCAEQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIgZAAQgEABgCABQgCABAAAEIABBdQAAABAAAAQAAABgBABQAAAAAAABQAAAAgBABIgEABg");
	this.shape_14.setTransform(-70.5,-79.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AACBAIgEAAIgGAAQgDgCAAgEIAAheQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBgBQgBgBgFAAIgKAAIgKAAIgEAAQgEAAgCgCIgBgHIAAgDIABgFIACgDIADgBIBYAAQAEAAABACQACADAAADIgBADIAAAFIgCAEQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIgZAAQgEABgCABQgCABAAAEIABBdQAAABAAAAQAAABgBABQAAAAAAABQAAAAgBABIgEABg");
	this.shape_15.setTransform(-86.5,-79.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgrBAIgEgBQgBgBAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAh2QAAAAAAAAQAAgBAAAAQABgBAAAAQAAAAABAAIAEgCIBZAAQAAAAABAAQAAABAAAAQABAAAAABQABAAAAABIABADIAAAFIAAADIgBAFIgDADIhCAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAgBAAQAAABgBAAQAAABAAAAQAAABgBABQAAAAAAABIAAARQAAAAAAABQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAQABAAAAAAIArAAQAAAAABABQAAAAABAAQAAAAAAAAQAAABABAAIABAEIAAAGIAAACQAAAGgFACIgpAAQgCgBgDADQAAABgBAAQAAABAAAAQAAABgBAAQAAABAAABIAAATQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAABABAAQAAAAABABQAAAAABAAQABAAAAAAIBCAAQAEACAAAFIAAAEIgBAFIgBAFQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAg");
	this.shape_16.setTransform(-97.4,-79.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AgKBBQgHAAgFgDIgMgGIgLgIQgFgFgDgFQgEgGgCgFQgGgNAAgOIABgNQACgHADgFQAFgNAJgJIALgHIAMgGIAMgFIANgBQAIAAAGABQAIACAHADQAOAHAKALIAAACIgCAFIgEAEIgFAEQgBAAAAAAQgBABAAAAQgBAAAAAAQgBABgBAAQgCAAgDgEIgGgFQgFgEgGgDQgGgCgJAAQgIgBgIAEQgIAEgGAGQgGAGgEAIQgDAIAAAIQAAAJADAIQAEAIAGAGQAGAHAIADQAIAEAIAAIAJgBIAJgDIAIgDQADgEACgEIABgBQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBgBIgEgBIgXAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAgBIgBgDIgBgGIAAgDIABgFQAAAAABgBQAAAAAAgBQABAAAAAAQABgBAAAAIA2AAIACABIADABQACAGAAAGIAAAGIgBAFQgFAKgFAIQgHAHgIAFQgIAGgKACQgJADgKAAIgNgCg");
	this.shape_17.setTransform(-112,-79.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.mainsides, new cjs.Rectangle(-121.4,-90.3,242.9,22.8), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.kalelogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgNAAgSQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAASgNANQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAPQAAANgNABIAPAWgAgHgDIAGAAQANAAAAgIQAAgHgMAAIgHAAg");
	this.shape.setTransform(35,15.9,0.269,0.269);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgVgDgGgEQgKgFAAgNQAAgKAFgHQAHgHAIAAIARAAQAKAAAFgLQACgKABgXIAAl5QgBgXgCgKQgFgLgKAAIgRAAQgIAAgHgHQgFgHAAgKQAAgNAKgFQAGgEAVgDQBdgNBrAAQBOAAA2ASQA0ASAnAoQAlAlAUA5QAUA4AABEQAABNgZA9QgaA+guAlQglAegxAOQgwAOhFAAQhrAAhdgNgAgwjrQgcAFgJALQgKAMAAAhIAAFjQAAAhAUALQAOAHAnADQBMAEAthAQAqg/AAhwQAAhwgqg/Qgrg/hKAAIgeADg");
	this.shape_1.setTransform(16.7,8.1,0.269,0.269);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgDAAgHIAAiTQAAgKgMAAIgyAAQgKAAAAgPIABgNQACgIAHAAICfAAQAMAAAAASQAAASgLAAIgyAAQgMAAAAAKIABCTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(21.8,23.7,0.269,0.269);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAAKgCADQgDAGgHAAIh5AAQgIAAAAAJIAAAbQAAAKAKAAIBFAAQALAAAAASQAAAQgKAAIhFAAQgLAAAAALIAAAeQAAAKAKAAIB4AAQAKAAAAATQAAARgKAAg");
	this.shape_3.setTransform(14,23.7,0.269,0.269);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAxBgIhAhGQgLgJgTAAQgFAAgEAEQgDAFAAAGIAAA8QAAAMgVAAQgRAAAAgNIAAi0QAAgIAFgCQAEgCALAAQASAAAAAMIAAA3QAAANAJAAQALAAAFgDQAEgBAFgFIBJhDQANgLAMAMQAMALgKAKIhAA6QgJAIAJAJIBOBWQAIAIgGAFQgFAFgNAAQgTAAgHgIg");
	this.shape_4.setTransform(6.1,23.7,0.269,0.269);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAuBeIgfgyQgGgJgKAAIgtAAQgDAAgEADQgEAEABADIAAAyQAAAGgKACIgPAAQgMAAAAgMIAAi5QgBgIAKAAIBqAAQAgAAAUATQAVATAAAfQAAAYgPAPQgIAJgPAKQgHAGADAGIAjAyQAFAIgFADQgEAFgPAAQgQAAgHgJgAg4g4IAAAuQAAAFAEADQAEACAFAAIA+AAQAQAAALgIQALgIAAgRQAAgQgLgJQgLgJgQABIg+AAQgNAAAAAKg");
	this.shape_5.setTransform(-3,23.7,0.269,0.269);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBgIgOgbQgCgHgHAAIhTAAQgJAAgEALIgMAXQgDAHgSAAQgWAAAFgMIBZi4QAFgKAKAAQALAAAFAJIBXC6QADAGgJAEQgGACgIAAQgPAAgDgIgAgEgdIgYAyQgDAIAIAAIAwAAQABAAABAAQAAAAABgBQABAAAAAAQAAgBABAAQACgCgCgDIgZgzQgBgDgEAAQgCAAgCADg");
	this.shape_6.setTransform(-11.9,23.7,0.269,0.269);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBkQgFgDAAgEIgOhsQgCgGgFAAQgDAAgDADIgxA+QgEAGgFAAQgHAAgEgHIgtg7QgCgDgEAAQgFAAgBAHIgOBoQgCALgTAAQgGAAgFgDQgGgDAAgFIAViwQACgJADgEQAEgEALAAQAKAAAFAJIA4BPQAFAHAEAAQAEAAAHgIIA7hQQAEgIALAAQAGAAADACQAEADACAIIAVC1QABALgXAAQgFAAgFgDg");
	this.shape_7.setTransform(-21,23.7,0.269,0.269);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgTQAmgTAngOQAKgDgDgJQgCgKgNADQg7ALgrgSQgWgJgdgRQghgUgJgEQgvgWg6AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgRQgggPgdgbQgfgcgvgCQgsgCgbAVQgLAIADAHQAEAHAKgDQAggHAdAGQAoAIAbAgQAkAoAuAPQA4ASAugfIAZgWQANgNAMAEQAPAEgBAUQgBAUgTAZQgiAsg+AeQhFAjgeAdQgwAwgTA9QgPAzAABQQAAByAqBAQAqBABKAAQBKAAArhCQAqhBAAhwQAAhfgXg4QgZg6g2gVQgbgKAFgTQAFgUAhgEQA3gGA8AsQBoBOAACjQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(3.9,-14.6,0.269,0.269);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDwQhFg1gYheIgBgCQgCgMgHAAQgGAAgCALIgBACQgYBfhGA1QhIA3hoAAQh+AAhMhQQhMhQAAiFQAAiHBMhRQBLhQCAAAQBpAABHA3QBHA2AXBgQACALAGAAQAHgBACgKIABgBQAXhgBGg1QBHg3BoAAQB/AABNBQQBMBPAACFQAACHhMBRQhNBRiBAAQhmAAhHg3gACniqQgpA/AABuQAABrApA/QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/gAmFiqQgoA/AABuQAABsAoA+QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/g");
	this.shape_9.setTransform(-5.6,8.1,0.269,0.269);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgJAAgYIAAl7QAAgXgDgKQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQAaAAAEAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOQgEgFgFgNQgFgQgPgFQgNgEggAAIhtAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAFADAdAAIBFAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgXIAAgFQgCgNgIgDQgHgEgbAAIhFAAQgeAAgEAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-26.4,8.1,0.269,0.269);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEbIgTgEQgIAAgKAJQgKAIgJAAQgLAAgGgHQgGgGgEgQIgVhUQgCgIAAgJQAAgMAHgIQAIgHAMAAQAMAAAJALIAMARQAWAfAhASQAiASAkAAQApAAAagVQAZgUAAgiQAAghgbgfQgbgdg/gsIhNg2QgSgPgTgWQgggmAAgzQAAg9ArgmQArgmBGAAQAlAAAjAIIAWAFIALACQAJAAALgIIAJgFQAEgCAFAAQASAAAGAYIAUBcQABAEAAAIQAAAIgHAGQgHAGgKAAQgMAAgLgOQgNgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAQAAAaQAAAXAJALQAMASAbAWIApAdQAzAkAWARQAXASAUAUQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgzAAglgNg");
	this.shape_11.setTransform(29.6,8.1,0.269,0.269);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah+EYQgLgJgHgYIhJjYQgBgFgEAAQgFAAgBAFIhNDYQgKAagHAHQgNAJgQAAQgTAAgKgJQgLgJgJgYIimm+QgKgagHgHQgHgHgUgFQgOgCgFgFQgFgFAAgLQAAgVAdgBICvAAQAcAAAAAYQAAAKgHAFQgHAFgRABQgOACgGAFQgGAFAAAJQAAAJADAKIBzFHQACAGAFgBQAEAAACgGIA/i2QAIgYgHgYIglhuQgEgJgHgFQgGgEgPgEQgNgDgGgGQgFgEAAgKQAAgaAdAAICnAAQAdAAAAAYQAAASgcAEQgRACgFAFQgGAFAAAMQAAAKAIAZIBfEsQACAFAEAAQAFAAABgGIBdk6QAEgLAAgJQAAgSgdgEQgbgCAAgVQAAgNAHgGQAIgFARgBIElAAQAVABAIAFQAIAFAAAOQAAAKgGAIQgGAGgJAAIgQAAQgLAAgFALQgCAIAAAZIAABtQAAAeAFAGQAGAHAXAAIB0AAQAXAAAHgIQADgDAAgHIABgdIAAhpQAAgbgDgGQgFgLgKAAIgQAAQgKAAgHgGQgGgIAAgKQAAgOAIgFQAJgFAWgBICaAAQAWABAJAFQAJAFAAAOQAAAKgHAIQgGAGgJAAIgSAAQgEAAgEADQgFADgBAFQgDAJAAAYIAAF9QAAAXADAKQABAFAFACQAEADAEABIASAAQAJAAAGAGQAHAIAAAJQAAAOgJAFQgIAGgXAAIiaAAQgWAAgIgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIAQAAQAKAAAFgLQADgGAAgbIAAh8IgBgeQAAgHgDgEQgHgHgXAAIh0AAQgXAAgGAGQgFAHAAAdIAACCQAAAYACAJQAFALALAAIAQAAQAJAAAGAGQAGAIAAAKQAAAOgIAEQgIAGgVAAIiaAAQgWAAgJgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIARAAQAEgBAFgDQAEgCABgFQADgGAAgbIAAl9QAAgwgkAEQgLABgHAKQgIAIgGAWIiHGzQgJAfgKALQgLALgTAAQgTAAgLgJg");
	this.shape_12.setTransform(-20.1,-9.9,0.269,0.269);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgWAAgIgFQgIgFAAgOQAAgKAGgHQAGgGAJAAIARAAQAEAAAEgDQAEgEACgEQADgIAAgXIAAl/QAAgZgDgJQgDgLgLABIgRAAQgKgBgGgGQgHgHAAgLQAAgNAJgGQAJgFAWAAICcAAQAWAAAJAFQAJAGAAANQAAALgGAHQgHAGgJABIgSAAQgOgBgDALQgDAGAAAcIAAFjQAAAdACAJQACAJAIAFQAGAEALACQALACAagBIAwAAQAvAAAPgfIAIgPQAIgQAPgBQAMAAAFAJQAFAJgEAQIgNBCQgEAVgaAAg");
	this.shape_13.setTransform(18.6,-10,0.269,0.269);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDABgEQAEgIAAgaIAAl7QAAgZgEgIQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgKQAAgNAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAIgMAAQgPAAgGgNQgDgCgGgQQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAEADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAIgOAAQgTAAgEgWIAAgFQgCgNgIgDQgHgEgbAAIgmAAQgeAAgEAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAPAFAiAAIBVAAQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgDALgHAFQgHAFgOAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(30.7,-10,0.269,0.269);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZNQk7iFjyjyQjyjziFk6QiJlFAAljQAAlkCJlFQCFk6DyjzQDzjyE6iFQFFiJFjAAQFkAAFFCJQE6CFDyDyQDyDzCGE6QCJFFAAFkQAAFjiJFFQiGE6jyDzQjyDyk6CFQlFCJlkAAQljAAlFiJg");
	this.shape_15.setTransform(0,0,0.269,0.269);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.kalelogo, new cjs.Rectangle(-47,-47,94,94), null);


(lib.holidaytipsrecipes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("Ag9BHQgbgcAAgoQABgrAbgcQAcgdApAAQAlAAAVAVQAWAVAAAiQgBAMgDAEQgEAEgOgBIhHAAQgGAAgEgCQgDgEAAgFQAAgEADgDQAEgDAGAAIAnAAIAJgBQADgCgBgEQAAgSgMgMQgMgNgRAAQgWAAgLAUQgLATAAAcQAAAcAPAWQAPAVAXAAQAOAAAJgDQAKgDAJgHIAHgEQAJgJAGABQAEAAACACQAEADAAAEQgBAFgFAGQgEAHgIAGQgRANgPAHQgPAFgRAAQgoAAgbgbg");
	this.shape.setTransform(128.7,34.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("Ag4BdQgJgDAAgIQAAgGAJgDIAFgDQAFgCACgHQACgGAAgPIgBgMIAAgQIAAgLQAAghgBgLQgCgKgEgCIgIgEQgMgEAAgGQAAgEAEgEQADgDAJgDIAZgIIARgEQAJABADAZIAAAEIABABQAKgQAKgIQALgIAKAAQANAAAIAIQAIAJAAAMQAAAOgGAHQgGAIgLgBIgJgBIgIgGIgEgHQgCgFgCAAQgNAAgFASQgFASAAA4QAAAQACAJQACAIAFADIAHACQAMAEAAAHQAAAHgLADQgKAEgZAAQgdAAgJgEg");
	this.shape_1.setTransform(112,34.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AhEBGQgagbgBgqQAAgqAcgcQAcgcAqAAQApAAAZAbQAaAaAAApQAAAqgcAeQgbAdgoAAQgpAAgbgcgAgjg3QgMAPAAAZQAAAkAQAaQAQAZAVAAQATAAAMgPQALgQAAgaQAAgkgQgZQgQgZgVABQgTAAgLAPg");
	this.shape_2.setTransform(93.8,34.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("ABGCEQgKgDAAgIQAAgIALgEIAJgFQADgCACgIQABgJAAgZIAAgKIgBhPIAAgvIgYA+Qg3CPgMAAQgGAAgKgTQgMgUgag9IgpheIgCBJIAAAzIABAjQABAIADACIAIAFQAMAEAAAIQAAAIgJADQgKAEgYAAQgUAAgJgEQgJgEAAgIQAAgGAKgFQAKgFABgDQACgKAEgwQACgwAAg7IAAgGQAAgUgBgGQgDgHgEgDIgJgEQgMgEABgIQAAgHAIgDQAJgDAbAAIAbABIAHABQADADAOAhIALAbIAFANQAuBxADAAQAEAAARgpQAQgnAYhDIAEgLQAGgVAGgGQADgDAIgCIAZgBQAZAAAJADQAIADABAHQAAAIgLAEIgGACQgFADgCAIQgCAHAAAdIACBrQACAvACAIQABAEAIADIAEABIAHAFQACADAAAEQAAAIgKADQgLAEgeAAQgdAAgKgEg");
	this.shape_3.setTransform(66.2,30.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AhxByQgjgbAAgsQAAgYALgTQAMgRAYgRIABgCQgIgIgEgJQgFgJAAgKQAAgeAXgTQAVgTAiAAQAYAAAPAJQAQAJgBAMQAAAEgDADQgEADgFAAIgPgEQgNgFgLAAQgQAAgIAJQgJAKAAARQAAAHACAFQADAGAEAFQAEAEAJAEIALAEIAEABIACADQAAAEgIAIQgGAHgGAAIgJgBIgNgFQgKAJgGANQgFAOAAAQQgBAkAYAYQAYAXAkAAQAeAAATgQQATgQAAgZQAAgQgIgJQgHgKgNAAQgOAAgIAIQgIAIAAAMIAAADIAAACIgDABIgCAAQgHAAgFgFQgDgFAAgJQAAgcBSglIAGgDQAVgKAMgMQAKgLABgNQgBgJgEgFQgFgEgKAAIgHABIgHABQgEAAgDgDQgCgDAAgEQAAgIAKgFQAKgGAQAAQAVAAALALQAMALAAATQAAAYgUATQgVATgpAQQARAGAJAOQAJAOAAAUQAAAOgGANQgFAOgLALQgRATgZAJQgbAKggAAQg5AAgjgbg");
	this.shape_4.setTransform(23.8,30.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgNBiIgUgEIgGAEIgGABIgEgBIgEgCQgGgGgFgPQgGgPAAgOQAAgGAEgEQADgEAFAAQAIAAAJAPIAHAMQAGAHAKAEQAJAFALAAQAMAAAHgHQAIgGAAgKQAAgQgfgPIgLgGQgdgOgLgMQgKgMAAgSQAAgYARgQQARgPAbAAIANABIANACIAJgEIAGgBQAJAAAJAPQAJAPAAAQQAAAHgDAEQgDADgGAAQgEAAgEgDQgEgEgGgJQgHgLgIgFQgHgFgLAAQgKAAgGAGQgHAHAAAKQAAAIAHAHQAHAGAWAMIACABQA1AZAAAfQAAAagUARQgVASgeAAg");
	this.shape_5.setTransform(-11.7,34.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("Ag9BHQgbgcAAgoQABgrAbgcQAcgdApAAQAlAAAWAVQAUAVABAiQgBAMgDAEQgDAEgOgBIhIAAQgGAAgEgCQgDgEAAgFQAAgEADgDQAEgDAGAAIAnAAIAJgBQADgCgBgEQAAgSgMgMQgMgNgRAAQgWAAgLAUQgLATAAAcQAAAcAPAWQAPAVAXAAQAOAAAJgDQAKgDAJgHIAHgEQAJgJAGABQAEAAACACQAEADAAAEQAAAFgGAGQgEAHgIAGQgRANgPAHQgPAFgRAAQgoAAgbgbg");
	this.shape_6.setTransform(-29.6,34.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AhbCAQgJgDAAgIQAAgGAIgDIAJgFQAEgEACgOQABgPAAgvIAAgeQAAgzgBgPQgCgPgFgCIgIgEQgMgDAAgGQAAgFAEgDQADgDAIgDIAagJQANgDAGAAQAGAAACADQACADAAAGIAAAJIABAEIAAABIAIgFIAHgFQAMgJAKgEQAKgEALAAQAjAAAXAZQAWAaAAApQAAAsgZAdQgZAdgnAAQgQAAgFgEQgHgFAAgIQAAgEADgDQADgDAGAAIAEABIAHABQAVAAAMgRQANgSAAgcQAAgggOgUQgOgUgVAAQgTAAgLALQgLALAAAcIAAB3IABATQABAIACACQACADAJACIAHADIAEADIACAGQAAAHgLADQgLACgbAAQgbAAgKgDg");
	this.shape_7.setTransform(-51.3,38);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AggCGQgKgDAAgIQAAgGAKgEIAEgCQAFgCACgHQACgGAAgPIAAgMIgBgQIAAgTQAAgegBgHQgBgKgEgBIgJgEQgMgEAAgGQAAgEAEgDQAEgDAIgEIAdgJIASgEQAFABADADQACAEAAAJIAAAKIgBAJIgBAvIAAACIAAAuQgBARACAIQACAHAEADIAHADQAKADAAAHQAAAHgKADQgJADgYABQgdAAgIgEgAgWheQgJgGABgKQgBgLAKgIQAIgHANgBQAMAAAHAIQAIAGAAALQAAAKgJAHQgIAIgMgBQgNABgHgHg");
	this.shape_8.setTransform(-67.2,30.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("Ag7BHQgbgcAAgoQAAgrAdgcQAcgdApAAQAfAAAWAQQAWARAAAVQAAAJgGAFQgHAGgJAAQgKgBgFgEQgGgFgHgPQgGgNgHgGQgHgFgMAAQgUAAgNAQQgMAQAAAdQAAAhASAVQARAWAaAAQAJAAAJgDQAIgCAHgFIAIgGQAKgIAFAAQAEAAADACQACACAAAEQAAAFgEAHQgEAGgGAGQgPANgQAGQgQAGgTAAQgmAAgbgbg");
	this.shape_9.setTransform(-82,34.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("Ag8BHQgbgcAAgoQAAgrAbgcQAbgdArAAQAkAAAVAVQAWAVgBAiQABAMgEAEQgEAEgOgBIhHAAQgGAAgDgCQgEgEAAgFQAAgEAEgDQADgDAGAAIAmAAIAKgBQADgCAAgEQAAgSgNgMQgMgNgRAAQgWAAgLAUQgLATAAAcQAAAcAPAWQAPAVAXAAQAOAAAKgDQAJgDAJgHIAHgEQAKgJAEABQAFAAADACQACADAAAEQAAAFgEAGQgFAHgIAGQgQANgPAHQgQAFgSAAQgnAAgagbg");
	this.shape_10.setTransform(-101.7,34.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AApBeQgSg8gOgMQgMgMgTAAQgPAAAAgMQAAgMAMAAQAfAAAPgMQAPgMAAgaQAAgYgPgNQgQgMgcAAQgPAAgFACQgGABgCAGIgCAQIgBAmIAABTIACA4QABANADADIAJAEQALAEAAAIQAAAIgKADQgKAEgeAAQgeAAgKgEQgLgDAAgIQAAgIAMgEIAIgFQAEgDACgWQACgWAAg7IgChHQgBgbgDgEQgCgCgKgEQgKgFAAgHQAAgGAGgEQAGgDAMAAIApAAIAmgBIAdgBQApAAAWASQAVARAAAiQAAAYgOATQgOASgaAHIAAACQAUAEAMAMQALANAJAeIAFATQAHAdALAAIAGAAIAHgBQADAAADADQADADAAAEQAAAJgLAFQgLAGgRAAQgmAAgMgsg");
	this.shape_11.setTransform(-124.7,30.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgUA5QgDgCAAgCIAEgHIADgGIALgUQAEgKAAgEIgBgFIgGgDQgKgEgFgGQgEgHAAgKQAAgNAIgIQAHgIAMAAQAMAAAIALQAIALAAARQAAAMgFANQgFAOgMAUIgJAPQgFAEgDAAQgFAAgEgCg");
	this.shape_12.setTransform(108.4,-0.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AgNBiIgUgEIgGAEIgGABIgEgBIgEgCQgGgGgFgPQgGgPAAgOQAAgGAEgEQADgEAFAAQAIAAAJAPIAHAMQAGAHAKAEQAJAFALAAQAMAAAHgHQAIgGAAgKQAAgQgfgPIgLgGQgdgOgLgMQgKgMAAgSQAAgYARgQQARgPAbAAIANABIANACIAJgEIAGgBQAJAAAJAPQAJAPAAAQQAAAHgDAEQgDADgGAAQgEAAgEgDQgEgEgGgJQgHgLgIgFQgHgFgLAAQgKAAgGAGQgHAHAAAKQAAAIAHAHQAHAGAWAMIACABQA1AZAAAfQAAAagUARQgVASgeAAg");
	this.shape_13.setTransform(94.5,-10.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AhbCAQgJgDAAgIQAAgGAIgDIAJgFQAEgEACgOQABgPAAgvIAAgeQAAgzgBgPQgCgPgFgCIgIgEQgMgDAAgGQAAgFAEgDQADgDAIgDIAagJQANgDAGAAQAGAAACADQACADAAAGIAAAJIABAEIAAABIAIgFIAHgFQAMgJAKgEQAKgEALAAQAjAAAXAZQAWAaAAApQAAAsgZAdQgZAdgnAAQgQAAgFgEQgHgFAAgIQAAgEADgDQADgDAGAAIAEABIAHABQAVAAAMgRQANgSAAgcQAAgggOgUQgOgUgVAAQgTAAgLALQgLALAAAcIAAB3IABATQABAIACACQACADAJACIAHADIAEADIACAGQAAAHgLADQgLACgbAAQgbAAgKgDg");
	this.shape_14.setTransform(74.8,-6.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AggCGQgKgDAAgIQAAgHAKgDIAEgCQAFgCACgHQACgGAAgOIAAgNIgBgPIAAgUQABgdgCgJQgBgJgEgBIgJgEQgMgDAAgHQAAgEAFgDQADgDAIgEIAcgJIATgEQAGAAACAEQACAEAAAIIAAALIgBAJIgBAvIAAACIAAAtQAAASABAIQACAHAEADIAHACQAKAEAAAHQAAAHgKAEQgJADgYAAQgdgBgIgDgAgWheQgJgHABgKQgBgLAKgHQAJgIAMAAQAMABAIAGQAHAHAAAKQAAALgJAHQgIAIgNAAQgMgBgHgGg");
	this.shape_15.setTransform(58.9,-14.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgnCGQgKgDAAgJQgBgHAKgEQALgEABgDQADgDABgfIABhYIAAgyIgCgeQgBgFgDgCQgEgBgHAAIgIAAQgNAAgHADQgHADgGAHIgFANIgGAMIgFAGQgEADgDAAQgGAAgCgFQgDgFAAgMQAAgZAFgPQAHgPAJAAIABAAQAQADAWAAIBuAAQAXAAAPgDIACAAQAJAAAGAPQAGAPAAAZQAAALgDAGQgCAFgHAAIgGgDIgFgGIgGgMIgFgNQgGgHgHgDQgIgDgMAAIgIAAQgIAAgDABQgDACgBAFIgCAeIAAAyIABBYQABAfACADQACADAKAEQAKAEAAAHQABAJgLADQgLADgdAAQgdAAgKgDg");
	this.shape_16.setTransform(41.4,-14.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AhWB8QgJgHAAgMQAAgKAHgGQAGgIAJAAIAIACIAGAEIAGAHQAFAIADgBQAKAAAKgNQAJgOABgPQAAgQgOgdIgCgFIgehBIgRglQgDgGgMgGQgGgCgDgCQgCgDAAgFQAAgIAKgDQAKgDAbAAQAcAAAJADQAJADAAAIIgBAFIgDAEIgHADQgHACAAAEIAEAOIAPAmIAOAjQAFAJADAAQACAAAFgIIALgfIAPglQAEgNAAgFQAAgGgKgFQgLgGAAgFQAAgGAJgDQAIgDAVAAQAXAAAHADQAJADgBAIQAAAGgKADIgIACQgKAHgMAfIgGAPIgYA8QgfBOgTAXQgUAYgcAAQgNAAgJgIg");
	this.shape_17.setTransform(9.6,-6.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E47").s().p("AAhBZIgKgKIgIAEQgWAPgYAAQgbAAgRgQQgRgQAAgZQAAgfAWgPQAWgRAnAAQAJAAAEACQAFADABAHQAAALgOAAQgRAAgMAJQgMAJABAQQAAAPAKAJQAJAJARAAQARAAAJgIQAHgJAAgTIAAhHQAAgRgHgJQgHgJgNAAQgJAAgIAFQgIAEgHAIIgEAFQgLAOgNAAQgIAAgEgEQgFgFABgIQgBgSAWgMQAWgMAiAAQAUAAAPAFQAQAGAHAKQAGAIADALQACAMAAAbIAAA7QAAALABAFQACAFAEABIAGACQAMADAAAHQAAAJgMAHQgNAHgRAAQgJAAgJgJg");
	this.shape_18.setTransform(-9.8,-10);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E47").s().p("AhSByQgWgaAAgpQAAgtAagcQAZgdAoAAIANABQAGACADAFQADADAAAGQAAAKgMAAIgFgBIgFAAQgVAAgMARQgNAQAAAeQAAAgAOATQANAUAWAAQATAAAKgLQALgLAAgVIAAg0IAAhVQAAgOgCgEQgDgFgHgDIgFgBQgLgEAAgGQAAgGAEgDQAFgEAOgFIAVgGIASgCQAGAAADADQADAEAAAIIgBAKIgCBzIACBPQABASADACIANAFQAKACAAAHQAAAJgbAIIgTAFIgOACQgGgBgCgDQgCgCAAgHIAAgJIgBgDIgBgBIgGADIgIAHQgLAIgKAEQgLAEgLAAQgkAAgWgZg");
	this.shape_19.setTransform(-30.6,-14.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006E47").s().p("AggCGQgKgDAAgIQAAgHAKgDIAEgCQAFgCACgHQACgGAAgOIAAgNIgBgPIAAgUQABgdgCgJQgBgJgEgBIgJgEQgMgDAAgHQAAgEAFgDQADgDAIgEIAcgJIATgEQAGAAABAEQADAEAAAIIAAALIgBAJIgBAvIAAACIgBAtQABASABAIQACAHAEADIAHACQAKAEAAAHQAAAHgKAEQgJADgYAAQgdgBgIgDgAgWheQgJgHABgKQgBgLAKgHQAJgIAMAAQAMABAIAGQAHAHAAAKQAAALgJAHQgIAIgNAAQgMgBgHgGg");
	this.shape_20.setTransform(-47.8,-14.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006E47").s().p("AgfCHQgJgDAAgIQAAgGAIgEIAJgFQADgDACgLIABgmIAAgdIAAgjIAAgOQAAgvgCgOQgCgOgEgCIgLgEQgMgDAAgHQAAgFAEgDQADgDAOgFIAZgHIATgCQAFAAADADQACAEAAAJIgBAOQgCBDAABDIACBAQABAOADAEIAKAFQAJAEAAAHQAAAHgJADQgKADgYAAQgcAAgJgDg");
	this.shape_21.setTransform(-58.6,-14.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006E47").s().p("AhEBHQgbgcAAgqQAAgpAcgdQAcgcAqAAQAoAAAaAbQAaAaAAApQAAArgcAdQgcAdgoAAQgoAAgbgbgAgjg3QgMAPAAAZQAAAkAQAaQAQAZAVAAQATAAAMgQQALgPAAgZQAAgkgQgZQgQgZgVAAQgTAAgLAPg");
	this.shape_22.setTransform(-74.1,-10);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006E47").s().p("AAqCEQgLgDAAgIQAAgIAMgEIAJgFQADgCABgMIACgsIgBgaIgBgHQgCgEgKgCQgJgBgjAAIgoABQgKABgDADIgCAFIgBAPIAAAPIABAsQACAMADACIAIAFQALAEAAAIQABAIgKADQgLAEgeAAQgdAAgLgEQgKgDAAgIQgBgIAMgEIAIgFQAFgCACgYQABgYAAg4IgBhGQgCgcgDgEQgBgCgKgEQgLgEABgIQAAgHAIgDQAJgDAhAAQAhAAAJADQAIADAAAHQAAAIgLAEIgIAEQgDADgCALIgCA4QABAHAHADQAHADAbAAIAPAAIAogBQALgBAEgDIACgEIABgHIAAgJIgCguQgBgKgDgCIgJgEQgMgEAAgIQAAgHAJgDQAKgDAgAAQAiAAAIADQAJACgBAIQAAAIgLAEIgJAEQgDADgCAaQgCAZAAAyIACBJQABAcADAEQABACAKAEQALAEgBAIQAAAIgKADQgLAEgdAAQgeAAgKgEg");
	this.shape_23.setTransform(-99,-14.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaytipsrecipes, new cjs.Rectangle(-140.6,-38.7,281.3,93.4), null);


(lib.holidayhostingtips = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgRB0IgXgDIgHADIgHABIgEgBIgFgCQgHgHgGgSQgHgRAAgRQAAgHAEgFQAEgFAFAAQALAAAKASIAJAOQAGAJAMAEQALAGANAAQAOAAAJgIQAJgHAAgNQAAgSglgSIgMgHQgjgRgNgOQgMgPAAgUQAAgeAUgSQAUgSAhgBIAPABIAQADIAKgEIAHgCQALABALARQAKASAAATQAAAIgDAFQgEAEgGAAQgGAAgFgEQgEgEgIgLQgHgOgKgFQgIgGgNAAQgMAAgIAHQgIAIAAALQAAALAIAHQAIAJAbAOIADABQA+AdAAAkQAAAggYAVQgYAVgkgBg");
	this.shape.setTransform(118.7,31.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AhsCYQgLgDAAgKQgBgHAKgEIALgGQAFgEABgSQACgRAAg4IAAgkQAAg9gCgRQgCgSgFgDIgKgEQgNgEAAgIQAAgFAEgEQAEgEAIgDIAggKQAPgEAHAAQAHAAACADQAEAEAAAIIAAALIAAAEIABABIAJgGIAIgGQAOgKAMgFQAMgFAOAAQApAAAbAeQAbAfgBAwQAAA1gdAjQgeAiguAAQgTAAgGgFQgIgGAAgJQAAgFADgDQAEgEAGAAIAGABIAIABQAZAAAOgVQAPgUAAgiQAAgmgQgYQgRgXgZAAQgWAAgOANQgNANAAAhIAACOIABAWQACAJACADQADADAKADIAJADIAEAEIADAHQAAAIgOAEQgNADggAAQggAAgLgEg");
	this.shape_1.setTransform(95.3,35.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgnCgQgLgEAAgKQAAgHALgEIAGgDQAFgDADgHQACgIAAgRIAAgPIgBgSIAAgXQAAgkgBgJQgCgLgEgCIgLgEQgOgFAAgHQAAgFAFgEQAEgEAKgEIAhgLIAYgEQAFAAADAEQADAFgBAKIAAANIAAAKIgBA5IAAABIgBA3QAAAVABAJQACAJAGACIAIAEQAMAEAAAJQAAAIgLAEQgMADgdAAQghAAgLgDgAgbhwQgKgIABgMQgBgMALgJQAKgJAQAAQAOAAAJAIQAJAIAAAMQAAAMgKAJQgKAJgPAAQgOAAgKgIg");
	this.shape_2.setTransform(76.3,26.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AguCgQgNgEAAgLQAAgIAMgFQAMgEACgEQADgEACglIAAhpIAAg7IgCgkQgBgFgEgDQgEgCgIAAIgKAAQgPABgKADQgIAEgGAJIgHAOIgGAPIgHAIQgEACgEAAQgHAAgDgFQgDgHAAgNQAAgeAHgSQAHgSALAAIACAAQASADAbAAICDAAQAbAAASgDIACAAQALAAAHASQAHASAAAeQAAANgDAHQgEAFgHAAIgHgCIgHgIIgGgPIgHgOQgGgJgJgEQgJgDgPgBIgJAAQgKAAgEACQgDADgBAFIgCAkIgBA7IABBpQACAlADAEQACAEAMAEQAMAFAAAIQAAALgNAEQgNADgiAAQgiAAgMgDg");
	this.shape_3.setTransform(55.5,26.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AhSCSQgdgRAAgZQAAgLAGgIQAGgHANAAQAJAAAFAFQAFAGADALQAFAQAPAJQAOAKAbAAQAdAAAUgMQAUgLAAgSQAAgKgIgGQgHgGgOAAIgaACIgiACQgoAAgVgNQgWgOAAgSQAAgMAIgKQAIgKAQgKQgNgLgHgOQgGgPAAgRQAAgkAbgZQAcgYAqAAIAXACIAiAHQAIAAAKgFQAKgDAOgKIAHAHIACAHQAAAKgHAIQgHAJgNAHIAHASIACASQAAAmgbAXQgbAXgrAAIgYgDIgVgEIgHAJIgCAIQAAALAKAEQALAGAWgBIAhgCIAjgDQAgAAAQANQARANAAAYQAAAjgjAYQgjAYg1gBQgrAAgcgRgAgkhuQgMAOAAAWQAAAXALAOQAMAOASAAQASAAANgOQAMgOAAgWQAAgXgMgOQgMgPgTAAQgRAAgMAPg");
	this.shape_4.setTransform(17.7,35.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AhtBvQgLgDAAgKQAAgIALgEIAFgDQAGgDADgHQACgIAAgRIAAgPIgBgSIAAgWQAAgkgBgKQgCgLgEgCIgLgEQgOgFAAgHQAAgFAFgDQAEgEAKgEIAggLIAXgEQAGABADADQADADAAAIIAAAPIAAACIABAAIACAAIABgBIAFgFIAFgEQAYgWAbgBQAQABAPAGQAPAIAKALQALAMAEARQAEASAAAjIAAAeIAAAOIAAAOQAAAPACAHQACAGAGADIAGADQALAEAAAIQAAAJgLAEQgKADgiAAQggAAgKgDQgLgEAAgIQAAgJALgDIAJgFQAFgCACgKQACgKAAgYQAAhHgJgSQgJgRgYgBQgLABgLAHQgKAHgGAMQgFAJgCASQgCARAAAsQAAAVACAIQACAHAEACIAJAFQALADAAAJQAAAIgLAEQgLADgdABQgigBgLgDg");
	this.shape_5.setTransform(-8.4,31.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgnCgQgLgEAAgKQAAgHALgEIAFgDQAHgDACgHQACgIAAgRIAAgPIAAgSIAAgXQAAgkgCgJQgBgLgFgCIgKgEQgOgFgBgHQABgFAEgEQAEgEAKgEIAigLIAWgEQAHAAACAEQADAFAAAKIAAANIAAAKIgDA5IAAABIgBA3QAAAVADAJQACAJAEACIAJAEQAMAEAAAJQAAAIgMAEQgKADgeAAQghAAgLgDgAgbhwQgKgIAAgMQAAgMALgJQALgJAOAAQAPAAAJAIQAKAIAAAMQAAAMgLAJQgLAJgOAAQgPAAgJgIg");
	this.shape_6.setTransform(-28.1,26.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgLCGQgMgDgIgIQgHgGgEgNQgDgMAAgiIAAh3IgVAAIgGgCIgCgFIAAgGQAAgHAXgUIAKgIIAIgIQAYgUAIAAIAGACQADACAAADIAAAqIAyAAQAFAAADADQABABAAAHIAAAFQAAAGgCACQgCADgFAAIguAAIgEACIgBAFIAABvQAAAcAFAIQAFAHANAAQAHAAALgEIAPgDQAFAAADACQAEADAAAFQAAAMgTAMQgTALgZAAQgMAAgLgEg");
	this.shape_7.setTransform(-42.1,29.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgQB0IgYgDIgHADIgGABIgFgBIgFgCQgHgHgHgSQgGgRAAgRQAAgHAEgFQAEgFAFAAQAKAAALASIAIAOQAIAJALAEQAMAGAMAAQAOAAAJgIQAJgHAAgNQAAgSglgSIgNgHQgjgRgMgOQgMgPAAgUQAAgeAUgSQAUgSAhgBIAPABIAPADIALgEIAHgCQALABAKARQALASAAATQAAAIgEAFQgDAEgHAAQgEAAgFgEQgFgEgHgLQgJgOgIgFQgJgGgNAAQgMAAgIAHQgIAIAAALQAAALAIAHQAIAJAbAOIADABQA+AdAAAkQAAAggXAVQgZAVgjgBg");
	this.shape_8.setTransform(-60,31.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AhRBUQggghAAgyQAAgyAighQAhgiAyAAQAwAAAfAgQAfAfAAAxQAAAzghAjQgiAigwAAQgwABggghgAgqhCQgOASAAAeQAAArATAeQATAfAaAAQAWAAAOgTQANgSAAgfQAAgqgTgfQgTgdgZAAQgWAAgOASg");
	this.shape_9.setTransform(-82.1,31.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AAxCeQgLgEAAgKQAAgJANgGIAKgEQAEgDACgOIABg1IAAgfIgCgIQgDgFgLgBQgKgCgqAAIgvABQgMABgFADIgCAHIgBARIAAASIABA1QACAOAEADIAKAEQANAGAAAJQAAAKgMAEQgMADgjABQgkgBgMgDQgNgEAAgKQABgJAOgGIAJgEQAFgEACgcQACgcAAhDIgChUQgCghgCgEQgDgDgMgFQgMgFAAgJQAAgJAKgDQALgDAoAAQAnAAAKADQAKADAAAJQAAAJgNAFIgKAGQgEADgCAOIgBBBQAAAKAIACQAIAEAhAAIASAAIAvgBQAOgCAEgEIACgDIABgJIAAgLIgBg3QgCgLgEgCIgKgGQgNgFAAgJQAAgJAKgDQAKgDAnAAQApAAAKADQAKADgBAJQAAAKgOAEIgKAGQgEADgCAfQgCAeAAA7IACBWQABAiADAEQACAEANAEQAMAFgBAJQAAAKgMAEQgMADgkABQgjgBgNgDg");
	this.shape_10.setTransform(-111.6,26.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AhnCUQgKgKgBgOQABgLAHgIQAJgIAKAAIAKACIAHAFIAHAIQAFAJAFAAQALAAALgQQAMgRAAgSQAAgSgPgkIgDgGIgjhNIgVgrQgEgIgNgHIAAAAQgIgCgDgDQgDgEAAgEQABgLALgDQAMgEAhAAQAgAAALADQALAEAAAJIgBAHIgEAEIgIAEQgIADAAAEIAEARIASAtIASApQAFAMAEAAQABAAAGgLIAOgjIARgtQAFgPAAgHQAAgFgNgIQgMgHAAgGQAAgHALgEQAKgDAZAAQAbAAAJADQAKAEAAAJQAAAIgNAEIgKACQgMAIgPAlIgGARIgdBIQgkBdgXAcQgYAcghAAQgQAAgLgJg");
	this.shape_11.setTransform(67.5,-16.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AAoBpIgMgMIgKAFQgbATgcAAQggAAgVgTQgTgTgBgfQAAgkAagTQAagUAvAAQALAAAFAEQAGADAAAIQAAANgPAAQgWAAgNAKQgOALAAATQAAASAMALQALAKAUAAQAVAAAKgJQAJgKAAgXIAAhVQAAgTgJgLQgIgLgQAAQgKAAgJAFQgKAFgJAKIgFAGQgNARgQAAQgJAAgFgGQgFgFAAgKQAAgVAagOQAagPApAAQAYAAASAHQASAGAJANQAHAIADAOQACAOAAAgIAABHQAAANADAGQACAGAEABIAHACQAPAEAAAIQAAALgQAIQgOAJgVAAQgKAAgKgMg");
	this.shape_12.setTransform(44.5,-21.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AhhCIQgbgfAAgwQAAg3AeghQAfgjAvAAIAQACQAHADAEAEQADAFAAAGQAAAMgOAAIgGAAIgGgBQgZAAgPAVQgPASAAAkQAAAmARAXQAQAYAZAAQAXAAANgNQANgNAAgZIAAg+IAAhlQAAgRgDgGQgDgFgJgEIgGgBQgNgEAAgIQAAgGAFgFQAFgEARgGIAZgHIAVgDQAIAAADAFQADAEAAAKIAAALIgCCKIABBdQACAWADACIAQAGQAMADAAAHQAAALghAKIgWAGIgRACQgGAAgDgDQgDgEAAgIIAAgLIAAgDIgCgDIgHAFIgJAIQgOAKgMAEQgNAGgNgBQgqAAgagdg");
	this.shape_13.setTransform(19.7,-26.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgnCgQgLgEAAgKQAAgHALgEIAGgDQAFgDADgHQACgIAAgRIAAgPIAAgSIAAgXQgBgkgBgJQgCgLgEgCIgKgEQgPgFAAgHQAAgFAFgEQAEgEAKgEIAhgLIAYgEQAFAAADAEQACAFABAKIAAANIAAAKIgCA5IAAABIgBA3QAAAVACAJQABAJAGACIAIAEQAMAEAAAJQgBAIgKAEQgLADgeAAQghAAgLgDgAgbhwQgKgIAAgMQAAgMALgJQAKgJAPAAQAPAAAJAIQAJAIAAAMQAAAMgKAJQgKAJgPAAQgOAAgKgIg");
	this.shape_14.setTransform(-0.8,-26.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AglChQgLgEAAgKQAAgHAJgEIALgGQAEgEACgNIACgsIgBgjIAAgqIAAgRQAAg4gCgRQgCgQgEgCIgOgFQgOgEAAgIQAAgGAEgDQAEgEAQgGIAegIIAXgDQAGAAADAEQADAEAAALIgBARQgCBPAABRIABBMQACAQADAFIANAGQAKAEAAAJQAAAIgLAEQgLADgdAAQghAAgLgDg");
	this.shape_15.setTransform(-13.6,-26.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AhRBUQggghAAgyQAAgxAigiQAhghAygBQAwABAfAfQAfAfAAAxQAAAzghAjQgiAigwAAQgwAAgggggAgqhCQgOASAAAeQAAArATAeQATAfAaAAQAWgBAOgSQANgSAAgfQAAgrgTgeQgTgdgZAAQgWAAgOASg");
	this.shape_16.setTransform(-32.1,-21.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AAyCeQgMgEgBgKQABgJAOgGIAKgEQADgDABgOIACg0IAAggIgCgJQgCgEgLgBQgLgCgqAAIgvABQgNABgDADIgDAHIgBARIAAATIACA0QABAOAEADIAJAEQAOAGABAJQAAAKgNAEQgMAEgkAAQgiAAgNgEQgMgEAAgKQAAgJANgGIAKgEQAFgEACgcQACgdAAhCIgChUQgCghgDgEQgCgDgLgFQgMgFAAgJQAAgJAKgDQAJgEApABQAngBAKAEQALADAAAJQgBAJgOAFIgJAGQgEADgBAOIgCBCQAAAJAIACQAJADAgABIASAAIAvgCQAOgBAEgDIADgFIAAgJIAAgKIgCg3QgBgLgDgCIgKgGQgOgFgBgJQAAgJALgDQALgEAnABQAogBAJAEQALADAAAJQAAAKgPAEIgJAGQgFADgCAeQgCAeAAA8IACBWQABAiAEAEQABAEAMAEQANAFAAAJQAAAKgNAEQgNAEgiAAQgkAAgMgEg");
	this.shape_17.setTransform(-61.6,-26.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidayhostingtips, new cjs.Rectangle(-130.6,-55.2,261.2,110.4), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("EgWVgteMAsrAAAMAAABa9MgsrAAAg");
	this.shape.setTransform(0,0,1.045,1.029);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-150.5,-300.5,301,601), null);


(lib.fourteentopright_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteentopright();
	this.instance.parent = this;
	this.instance.setTransform(-41.5,-80);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteentopright_1, new cjs.Rectangle(-41.5,-80,83,160), null);


(lib.fourteentopleft = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteenpietopleft();
	this.instance.parent = this;
	this.instance.setTransform(-96.5,-68);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteentopleft, new cjs.Rectangle(-96.5,-68,193,136), null);


(lib.fourteentable_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteentable();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteentable_1, new cjs.Rectangle(-150,-300,300,600), null);


(lib.bottomright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteenbottomright();
	this.instance.parent = this;
	this.instance.setTransform(-105,-130.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bottomright, new cjs.Rectangle(-105,-130.5,210,253), null);


(lib.bottomleft = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteenbottomleft();
	this.instance.parent = this;
	this.instance.setTransform(-41,-80);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bottomleft, new cjs.Rectangle(-41,-80,82,160), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.seventeenrollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(7));

	// rollover
	this.instance = new lib.seventeenrollovervideo();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-71.2,-12.7,142.5,35.5);


// stage content:
(lib.halfpagebannerfourteen = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_54 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_211 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(54).call(this.frame_54).wait(157).call(this.frame_211).wait(4));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(150.3,301.6,1.456,0.919,0,0,0,0.2,0.1);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(215));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(215));

	// fade-from-white
	this.instance_1 = new lib.blackwideskyscraper();
	this.instance_1.parent = this;
	this.instance_1.setTransform(150.2,300,1.826,1,0,0,0,0.1,0);
	this.instance_1.filters = [new cjs.ColorFilter(0, 0, 0, 1, 255, 255, 255, 0)];
	this.instance_1.cache(-84,-302,168,604);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},9).wait(206));

	// kale-logo
	this.instance_2 = new lib.kalelogo();
	this.instance_2.parent = this;
	this.instance_2.setTransform(150,37);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({scaleX:0.09,scaleY:0.09},0).to({scaleX:1.07,scaleY:1.07,alpha:1},6,cjs.Ease.get(1)).to({regX:0.1,regY:0.1,scaleX:1,scaleY:1,x:150.1,y:37.2},7,cjs.Ease.get(1)).wait(193));

	// get-the-party-started
	this.instance_3 = new lib.mainsides();
	this.instance_3.parent = this;
	this.instance_3.setTransform(150,272.5);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(194).to({alpha:1},10).wait(11));

	// holiday-tips-recipes-more
	this.instance_4 = new lib.holidaytipsrecipes();
	this.instance_4.parent = this;
	this.instance_4.setTransform(150,249.7);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(199).to({alpha:1},10).wait(6));

	// sweet-inspiration
	this.instance_5 = new lib.sweetinspiration();
	this.instance_5.parent = this;
	this.instance_5.setTransform(150,231);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(134).to({alpha:1},10).wait(40).to({alpha:0},5).wait(26));

	// holiday-hosting-tips
	this.instance_6 = new lib.holidayhostingtips();
	this.instance_6.parent = this;
	this.instance_6.setTransform(150,231);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(94).to({alpha:1},10).wait(30).to({alpha:0},5).wait(76));

	// party-ready-recipes
	this.instance_7 = new lib.seventeenwhatsinourfest();
	this.instance_7.parent = this;
	this.instance_7.setTransform(150,256.7);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(44).to({alpha:1},10).wait(40).to({alpha:0},5).wait(116));

	// order-now
	this.instance_8 = new lib.ordernow();
	this.instance_8.parent = this;
	this.instance_8.setTransform(150,347.3);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(54).to({y:346.3},0).to({alpha:1},10).wait(151));

	// cta-rollover
	this.cta_rollover = new lib.seventeenrollover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(150,346.8);
	this.cta_rollover.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(54).to({alpha:1},10).wait(151));

	// cta-rectangle
	this.instance_9 = new lib.seventeenrectangle();
	this.instance_9.parent = this;
	this.instance_9.setTransform(150,346.8);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(54).to({alpha:1},10).wait(151));

	// top-left
	this.instance_10 = new lib.fourteentopleft();
	this.instance_10.parent = this;
	this.instance_10.setTransform(96.5,68);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(14).to({alpha:1},10).wait(191));

	// bottom-right
	this.instance_11 = new lib.bottomright();
	this.instance_11.parent = this;
	this.instance_11.setTransform(195,477.5);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(20).to({alpha:1},10).wait(185));

	// bottom-left
	this.instance_12 = new lib.bottomleft();
	this.instance_12.parent = this;
	this.instance_12.setTransform(41,520);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(26).to({alpha:1},10).wait(179));

	// top-right
	this.instance_13 = new lib.fourteentopright_1();
	this.instance_13.parent = this;
	this.instance_13.setTransform(258.5,80);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(34).to({alpha:1},10).wait(171));

	// table
	this.instance_14 = new lib.fourteentable_1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(215));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,290,300,613);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/index_atlas_.jpg", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;